-- =============================================================================
-- wms-cpc: WMS-only DDL (shades, fabric_rolls, receipt location split, item FKs)
-- Aligns with backend/models.py. Does NOT create or alter core.* tables.
--
-- Prerequisites (must already exist):
--   - Schemas: core, wms
--   - core.clients(client_id), core.colors(color_id), core.materials(material_id)
--   - wms.warehouses, wms.warehouse_racks, wms.logical_locations, wms.boxes
--   - wms.receipts, wms.receipt_items
--
-- PostgreSQL 11+ recommended (ADD COLUMN IF NOT EXISTS).
-- Backup the database before running.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Schemas (safe if already present)
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS wms;

-- -----------------------------------------------------------------------------
-- 1. WMS enum types (idempotent — no-op if type already exists)
-- -----------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE wms.warehouse_type AS ENUM ('Fabric', 'RMG', 'Accessory');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE wms.receipt_type AS ENUM ('inbound', 'dyehouse', 'internal', 'shipping');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE wms.receipt_status AS ENUM ('issued', 'confirmed', 'cancelled');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE wms.transaction_type AS ENUM ('IN', 'OUT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE wms.logical_location_type AS ENUM ('client', 'dyehouse', 'internal');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- logical_locations table is a prerequisite; add Location Type when missing
ALTER TABLE wms.logical_locations
  ADD COLUMN IF NOT EXISTS location_type wms.logical_location_type NOT NULL DEFAULT 'internal';

-- -----------------------------------------------------------------------------
-- 2. wms.shades
--     FKs reference core.clients(client_id) and core.colors(color_id) — not "id".
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wms.shades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES core.clients(client_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    color_id INTEGER NOT NULL REFERENCES core.colors(color_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    shade_number INTEGER NOT NULL,
    CONSTRAINT uq_wms_shades_client_color_number UNIQUE (client_id, color_id, shade_number),
    CONSTRAINT ck_wms_shades_positive_number CHECK (shade_number > 0)
);

CREATE INDEX IF NOT EXISTS ix_wms_shades_client_color ON wms.shades (client_id, color_id);

-- -----------------------------------------------------------------------------
-- 3. wms.fabric_rolls (requires wms.warehouse_racks and wms.shades)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wms.fabric_rolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_id VARCHAR(50) NOT NULL UNIQUE,
    barcode VARCHAR(100) UNIQUE,
    client_id INTEGER NOT NULL REFERENCES core.clients(client_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    color_id INTEGER REFERENCES core.colors(color_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    material_id INTEGER NOT NULL REFERENCES core.materials(material_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    lot_number VARCHAR(50),
    gsm NUMERIC(6,2),
    fabric_width NUMERIC(6,2),
    weight_kg NUMERIC(8,3) NOT NULL,
    meterage NUMERIC(8,2),
    status VARCHAR(3) NOT NULL DEFAULT 'in',
    rack_id INTEGER REFERENCES wms.warehouse_racks(id) ON UPDATE CASCADE ON DELETE SET NULL,
    defect_points INTEGER DEFAULT 0,
    quality_grade VARCHAR(20),
    shade_id INTEGER REFERENCES wms.shades(id) ON UPDATE CASCADE ON DELETE SET NULL,
    received_date TIMESTAMP,
    issued_date TIMESTAMP,
    supplier VARCHAR(100),
    remarks TEXT,
    CONSTRAINT ck_fabric_rolls_status CHECK (status IN ('in', 'out'))
);

-- -----------------------------------------------------------------------------
-- 4. Optional: migrate legacy receipt_type value 'cutting' → 'internal'
--     Only if your enum still has 'cutting' and rows use it. Skip on fresh DBs.
-- -----------------------------------------------------------------------------
-- ALTER TYPE wms.receipt_type ADD VALUE 'internal';
-- UPDATE wms.receipts SET receipt_type = 'internal'::wms.receipt_type
--   WHERE receipt_type::text = 'cutting';

-- -----------------------------------------------------------------------------
-- 5. wms.receipts — split source/target locations
--     Required for the current Receipt ORM (GET /api/v1/receipts). Can be run alone:
--     see migrate_wms_receipts_location_columns.sql
--     Backfill from legacy source_location_id / target_location_id before dropping them.
-- -----------------------------------------------------------------------------
ALTER TABLE wms.receipts
  ADD COLUMN IF NOT EXISTS source_warehouse_id INTEGER REFERENCES wms.warehouses(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS source_logical_location_id INTEGER REFERENCES wms.logical_locations(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS target_warehouse_id INTEGER REFERENCES wms.warehouses(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS target_logical_location_id INTEGER REFERENCES wms.logical_locations(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Backfill examples (customize per your legacy rules):
-- UPDATE wms.receipts SET source_warehouse_id = source_location_id WHERE ... ;
-- UPDATE wms.receipts SET source_logical_location_id = source_location_id WHERE ... ;

ALTER TABLE wms.receipts DROP CONSTRAINT IF EXISTS ck_receipts_source_one_location_type;
ALTER TABLE wms.receipts DROP CONSTRAINT IF EXISTS ck_receipts_target_one_location_type;

ALTER TABLE wms.receipts
  ADD CONSTRAINT ck_receipts_source_one_location_type
    CHECK (NOT (source_warehouse_id IS NOT NULL AND source_logical_location_id IS NOT NULL)),
  ADD CONSTRAINT ck_receipts_target_one_location_type
    CHECK (NOT (target_warehouse_id IS NOT NULL AND target_logical_location_id IS NOT NULL));

-- After backfill:
-- ALTER TABLE wms.receipts DROP COLUMN IF EXISTS source_location_id;
-- ALTER TABLE wms.receipts DROP COLUMN IF EXISTS target_location_id;

-- -----------------------------------------------------------------------------
-- 6. wms.receipt_items — roll_id BIGINT + FKs to fabric_rolls and boxes
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'wms' AND table_name = 'receipt_items'
      AND column_name = 'roll_id'
      AND data_type = 'integer'
  ) THEN
    ALTER TABLE wms.receipt_items
      ALTER COLUMN roll_id TYPE BIGINT USING roll_id::bigint;
  END IF;
END $$;

ALTER TABLE wms.receipt_items DROP CONSTRAINT IF EXISTS fk_receipt_items_roll;
ALTER TABLE wms.receipt_items DROP CONSTRAINT IF EXISTS fk_receipt_items_box;

ALTER TABLE wms.receipt_items
  ADD CONSTRAINT fk_receipt_items_roll
    FOREIGN KEY (roll_id) REFERENCES wms.fabric_rolls(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE wms.receipt_items
  ADD CONSTRAINT fk_receipt_items_box
    FOREIGN KEY (box_id) REFERENCES wms.boxes(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- =============================================================================
-- Verification (optional)
-- =============================================================================
-- SELECT typname, enumlabel FROM pg_enum e
--   JOIN pg_type t ON t.oid = e.enumtypid
--   JOIN pg_namespace n ON n.oid = t.typnamespace
-- WHERE n.nspname = 'wms' AND t.typname = 'receipt_type'
-- ORDER BY enumsortorder;
--
-- SELECT ri.id FROM wms.receipt_items ri
--   LEFT JOIN wms.fabric_rolls f ON ri.roll_id = f.id
--   WHERE ri.roll_id IS NOT NULL AND f.id IS NULL;
-- =============================================================================
